# Generated by Django 4.1.5 on 2023-01-16 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('Fundacja', 'Fundacja'), ('Organizacja Pozarządowa', 'Organizacja Pozarządowa'), ('Zbiórka Lokalna', 'Zbiórka Lokalna')], default='Fundacja', max_length=40)),
                ('categories', models.ManyToManyField(to='projectapp.category')),
            ],
        ),
    ]
